Repository ThomasTJdev/nim_websitecreator, pull requests merged in 2019-05, with the labels that each got.

#101 Working docker example
  README.md
  devops/Dockerfile
  devops/docker/Dockerfile
  devops/docker/base/Dockerfile
  devops/docker/build_docker.sh
  devops/docker/config.cfg
  devops/docker/run_docker.sh
  devops/run_docker.sh
Labels: enhancement

#88 Improve UX by using HTML Tools
  README.md
  nimwcpkg/tmpl/pageedit.tmpl
  nimwcpkg/tmpl/plugins.tmpl
  nimwcpkg/tmpl/settings.tmpl
  nimwcpkg/tmpl/user.tmpl
  nimwcpkg/tmpl/utils.tmpl
Labels: enhancement

#102 Fix #93
  README.md
Labels: enhancement

#107 Recommended Community Standards
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#105 build/update docker base
  devops/docker/Dockerfile
  devops/docker/base/Dockerfile
  devops/docker/build_docker.sh
  devops/docker/update_base.sh
Labels: enhancement

#103 Fix #92
  devops/autoinstall.sh
Labels: enhancement

#104 Fix #76
  nimwcpkg/resources/administration/create_standarddata.nim
  public/css/style.css
Labels: demo, enhancement
